jwt:
  secret: ${JWT_SECRET}
  access-expire-minutes: 10
  refresh_token_long_expire_days: 14
  refresh_token_short_expire_days: 1

server:
  port: 15554

spring:
  # 시스템 기본 타임존을 'Asia/Seoul'로 설정
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: Asia/Seoul
  # 레디스 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost} # 환경 변수가 없을 경우 localhost
      port: ${REDIS_PORT:6379}      # 환경 변수가 없을 경우 6379
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # 스프링 메일
  mail:
    host: smtp.naver.com           # 네이버 SMTP 서버 호스트
    port: 587                      # 보안 연결(TLS)을 위한 포트
    username: ym970825  
    password:  ${NAVER_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true               # SMTP 인증 사용
          starttls:
            enable: true           # TLS(Transport Layer Security) 사용
            required: true         # TLS 연결 필수

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.todoMarster
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'

logging:
  level:
    # SQL 쿼리가 포함된 로그를 DEBUG 레벨로 출력하도록 설정
    com.todoMaster: DEBUG # [선택] 본인 프로젝트의 루트 패키지 (예: com.todoMaster)
    
    # MyBatis가 DB 작업을 처리하는 매퍼 인터페이스의 패키지 경로를 DEBUG로 설정 (필수)
    # 아래 예시는 'com.todoMaster.user.mapper' 경로에 매퍼가 있다고 가정합니다.
    # com.todoMaster.user.mapper: DEBUG 
    
    # [선택] P6Spy 로그 출력을 보장하기 위해 DEBUG 설정
    com.p6spy: DEBUG

#  asw s3 연결 설정
aws:
  s3:
    bucket: todolist-bucketvivi
    region: ap-northeast-2
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}

oauth:
  # 카카오 소셜 로그인
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/auth/kakao/callback
  # 구글 소셜 로그인
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/auth/google/callback
